openai_api_base: "http://host.docker.internal:8001/v1"
openai_api_base2: "http://host.docker.internal:8002/v1"
openai_api_base3: "http://host.docker.internal:8004/v1"
openai_api_key: "local-key"
service_base_url: "http://localhost:9070"
service_container_name: "paper-curator-grobid"
